[package]
name = "strategies"
version = "0.1.0"
edition = "2024"

[dependencies]
core-types = { path = "../core-types" }
ta = "0.5"
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
rust_decimal = "^1.32"
serde_json = "1.0.140"
yata = "0.6"
