[package]
name = "strategies"
version = "0.1.0"
edition = "2024"

[dependencies]
core-types = { path = "../core-types" }
ta = "0.5"
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"