[workspace]
resolver = "2"

members = ["app"
    # We will add our application and library crates here in later tasks
, "crates/api-client", "crates/config", "crates/core-types", "crates/database", "crates/web-server"]
