[package]
name = "risk"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
core-types = { path = "../core-types" }
serde = { version = "1.0", features = ["derive"] }
rust_decimal = "1.34"
rust_decimal_macros = "1.34"
num-traits = "0.2"