[package]
name = "analytics"
version = "0.1.0"
edition = "2024"

[dependencies]
core-types = { path = "../core-types" }
rust_decimal = "1.33"
rust_decimal_macros = "1.33"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }