# In config/base.toml
# Default settings for all environments.
# These can be overridden by environment-specific files or environment variables.

[app]
environment = "development"
log_level = "debug"
# Default to using all available cores.
optimizer_cores = 0
[database]
# The database URL will be provided by environment-specific files or env vars.
# We put a dummy value here as a placeholder.
url = "postgres://postgres:root@localhost/atlas_db"

[server]
host = "127.0.0.1" # Listen on localhost by default
port = 8080