
[app]
# Override the log level for development to get more detailed logs.
log_level = "debug"

[binance]
api_key = "okgjgXGuaMqco4WrLGkcBYwZnvN3HNuTlMYqzqwkRbGySKUrTopXBPPVFVQS0ZVQ"
secret_key = "rGAosDtNGMUFotn6yO2EViX9oy4AINQMNYzJgk0Xjw4sdeV0ZOE5sfPGt5TPIuB3"

[database]
url = "postgres://postgres:root@localhost:5432/atlas_dev"