
[app]
# Override the log level for development to get more detailed logs.
log_level = "debug"

[binance]
api_key = "okgjgXGuaMqco4WrLGkcBYwZnvN3HNuTlMYqzqwkRbGySKUrTopXBPPVFVQS0ZVQ"
secret_key = "rGAosDtNGMUFotn6yO2EViX9oy4AINQMNYzJgk0Xjw4sdeV0ZOE5sfPGt5TPIuB3"

[database]
url = "postgres://postgres:root@localhost:5432/atlas_dev"

[simple_risk_manager]
# The fraction of the total portfolio to risk per trade (1% = 0.01)
risk_per_trade_percent = 0.01

# The percentage distance from entry to place the stop-loss (2% = 0.02)
stop_loss_percent = 0.02

# The minimum signal confidence required to consider a trade (60% = 0.60)
minimum_confidence_threshold = 0.60

[strategies.ma_crossover]
h1_fast_period = 10
h1_slow_period = 30
m5_fast_period = 5
m5_slow_period = 20
confidence = 0.8

[simulation]
# Binance Futures VIP 0 fees: 0.02% maker, 0.04% taker
maker_fee = 0.0002
taker_fee = 0.0004

# A reasonable assumption for slippage on a market order for a liquid pair
slippage_percent = 0.0005 # 0.05%