
[app]
# Override the log level for development to get more detailed logs.
log_level = "debug"
live_trading_enabled = true
[binance]
api_key = "31fbf16926ce01bfbf2dad27e1c087fc89749d9c1ea8d5c45db3c4c99620c920"
secret_key = "9ae595bb00812a75a3f1f43932599eba8177d668690a664eaea5c0f0071b9431"
# For Paper Trading (Testnet)
rest_base_url = "https://testnet.binancefuture.com" # <-- IT IS SET HERE
ws_base_url = "wss://fstream.binancefuture.com"

# For Live Trading (Production) - for future use
# rest_base_url = "https://fapi.binance.com"
# ws_base_url = "wss://fstream.binance.com"
[database]
url = "postgres://postgres:root@localhost:5432/atlas_dev"

[simple_risk_manager]
# The fraction of the total portfolio to risk per trade (1% = 0.01)
risk_per_trade_percent = 0.01

# The leverage to use for positions (e.g., 5 for 5x, 10 for 10x)
leverage = 10

# The percentage distance from entry to place the stop-loss (2% = 0.02)
stop_loss_percent = 0.02

# The minimum signal confidence required to consider a trade (60% = 0.60)
minimum_confidence_threshold =0

# [strategies.ma_crossover]
# h1_fast_period = 5
# h1_slow_period = 40
# m5_fast_period = 10
# m5_slow_period = 20
# confidence = 1
[strategies.ma_crossover]
h1_fast_period = 1
h1_slow_period = 2
m5_fast_period = 1
m5_slow_period = 2
confidence = 1
# [strategies.supertrend]
# period = 45
# multiplier = 2.0
# exit_multiplier = 1.5
# volume_threshold = 1000.0 # Min volume of base asset (e.g., BTC) per bar
# confirmation_bars = 1
# ema_confirmation_period = 20
# confidence = 0.30 # 80%

[strategies.prob_reversion]
bband_period = 20
bband_stddev = 1.8
adx_period = 14
adx_range_threshold = 30.0 # Only trade if ADX is below this (ranging market)
rsi_period = 14
rsi_smoothing = 5 # SMA of RSI
rsi_oversold = 30.0 # RSI level to start looking for a buy
confidence = 1.0 # 100%

[simulation]
# Binance Futures VIP 0 fees: 0.02% maker, 0.04% taker
maker_fee = 0.0002
taker_fee = 0.0004

# A reasonable assumption for slippage on a market order for a liquid pair
slippage_percent = 0.0005 # 0.05%