[[pairs]]
symbol = "BTCUSDT"
interval = "1m"
max_loss_per_asset_percent = 1.0
enabled = true

[[pairs.strategies]]
name = "supertrend"
weight = 1.0
[pairs.strategies.params]
period = 12
multiplier = 2.2
exit_multiplier = 1.6
confirmation_bars = 2
ema_confirmation_period = 20
volume_threshold = 1000.0
confidence = 0.8

[[pairs.strategies]]
name = "prob_reversion"
weight = 0.5
[pairs.strategies.params]
bband_period = 20
bband_stddev = 2.0
adx_period = 14
adx_range_threshold = 28.0
rsi_period = 14
rsi_smoothing = 3
rsi_oversold = 30.0
confidence = 0.9

[[pairs]]
symbol = "ETHUSDT"
interval = "1m"
max_loss_per_asset_percent = 1.0
enabled = true

[[pairs.strategies]]
name = "ma_crossover"
weight = 1.0
[pairs.strategies.params]
m5_fast_period = 12
m5_slow_period = 26
h1_fast_period = 50
h1_slow_period = 200
confidence = 0.75