[package]
name = "core-types"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
rust_decimal = { version = "1.33", features = ["serde-str"] }
toml = "0.8"